arm_plan_node:
  ros__parameters:
    debug: true
    planning_group_name: "mini_arm_group"
    joints_num: 6
    end_effector_link_name: "cc"

    command_in_type: "geometry_msgs/TwistStamped"
    command_in_topic: "/servo_server/delta_twist_cmds"
    servo_frame_id: "base_link"          # 接收速度的参考坐标系
    root_frame_id: "base_link"
    publish_period_ms: 10                # 控制频率 (ms)
    scale_linear: 0.2                    # 线速度缩放
    scale_angular: 0.2                   # 角速度缩放
    collision_check: true